python.path=/Users/samuel/Documents/Proyectos/QuTe/qute_venv/bin
python.executable=/Users/samuel/Documents/Proyectos/QuTe/qute_venv/bin/python
python.working.directory=/Users/samuel/Documents/Proyectos/QuTe/qute-backend
